name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'userbotindo/Anjani'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get release tag
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Anjani ${{ env.VERSION_TAG }}
          draft: true
          prerelease: false

  release:
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'userbotindo/Anjani'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.4.0"

      - name: Build
        run: |
          poetry build

      - name: Publish Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
